import { Geist as geist, Geist_Mono as giestMono } from "next/font/google"
import type { Metadata } from "next"
import "./globals.css"

const geistSans = geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const geistMono = giestMono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
